# Generated by Django 4.2 on 2023-04-09 13:41

from django.db import migrations, models
import quicktechpoints.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('body', models.TextField()),
                ('is_published_to_facebook', models.BooleanField(default=False)),
                ('is_published_to_twitter', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=False)),
                ('views', models.IntegerField(default=0)),
                ('keywords', models.CharField(blank=True, max_length=255)),
                ('image', models.ImageField(upload_to=quicktechpoints.models.article_image_file_path)),
                ('likes', models.TextField(blank=True)),
                ('dislikes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tag', models.ManyToManyField(related_name='articles', to='quicktechpoints.tag')),
            ],
        ),
    ]
