# Generated by Django 4.2 on 2023-04-09 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quicktechpoints', '0002_alter_user_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
