# Generated by Django 4.2 on 2023-04-09 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quicktechpoints', '0003_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='description',
            field=models.CharField(default='', max_length=500),
        ),
    ]
